services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ecomart-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - ecomart-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  backend-api:
    build: ./backend
    env_file:
      - ./backend/.env.production
    environment:
      - NODE_ENV=production
    container_name: ecomart-backend
    command: npm run start:prod
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ecomart-net
  frontend:
    build: ./frontend
    container_name: ecomart-frontend
    env_file:
      - ./frontend/.env.production
    ports:
      - "3000:3000"
    networks:
      - ecomart-net

  email-worker:
    build: ./backend
    env_file:
      - ./backend/.env.production
    environment:
      - NODE_ENV=production
    container_name: ecomart-email-worker
    command: npm run worker:prod
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ecomart-net

networks:
  ecomart-net:
    driver: bridge
